jobs:

- job: DeployBackend

  displayName: "Deploy Backend Container"

  pool:
    vmImage: "ubuntu-latest"


  steps:


  # Download SSH Key
  - task: DownloadSecureFile@1
    name: sshKey
    displayName: "Download SSH Private Key"
    inputs:
      secureFile: shopkart-ssh-key


  # Deploy Backend
  - task: SSH@0

    displayName: "Deploy Backend on VM"

    inputs:

      sshEndpoint: $(BACKEND_SSH_SERVICE_CONNECTION)

      runOptions: inline

      inline: |

        echo "Logging into ACR"

        docker login $(ACR_LOGIN_SERVER) \
        -u $(ACR_USERNAME) \
        -p $(ACR_PASSWORD)


        echo "Pulling latest backend image"

        docker pull $(ACR_LOGIN_SERVER)/$(BACKEND_IMAGE_NAME):v1


        echo "Stopping old container"

        docker stop backend-container || true


        docker rm backend-container || true


        echo "Starting new backend container"


        docker run -d \
        --name backend-container \
        -p 8080:8080 \
        --restart always \
        $(ACR_LOGIN_SERVER)/$(BACKEND_IMAGE_NAME):v1