trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: shopkart-variable-group

stages:

# ==========================
# Build Frontend
# ==========================

- stage: BuildFrontend
  displayName: Build Frontend Image

  jobs:
    - template: templates/build-frontend.yml


# ==========================
# Build Backend
# ==========================

- stage: BuildBackend

  displayName: Build Backend Image

  dependsOn: BuildFrontend

  jobs:
    - template: templates/build-backend.yml